package com.ntu.cz3003.CMS;

import android.util.Log;

import com.google.android.gms.tasks.OnSuccessListener;
import com.google.firebase.firestore.DocumentReference;
import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.GeoPoint;
import com.ntu.cz3003.CMS.models.Incident;

import java.util.Date;

import static com.ntu.cz3003.CMS.Constants.CMS_STATUS_PENDING;

public class DataGenerator {
    public static void main(String[] args){
        GeoPoint geoPoint = new GeoPoint(1, 1);
        Incident incident = new Incident();
        incident.setCreatedAt(new Date());
        incident.setCreatedBy("ewzukWyRN8TVXSPuRulJrXCH3n32");
        incident.setDescription("data generated by generator");
        incident.setIncidentNo("Generator001");
        incident.setLocation(geoPoint);
        incident.setLocationDescription("Generator Location");
        incident.setStatus(CMS_STATUS_PENDING);
        incident.setTitle("Generator Data Test");
        incident.setType("Flood");
        incident.setUpdatedAt(new Date());
        incident.setImageUri("https://firebasestorage.googleapis.com/v0/b/cz3003-cms-52714.appspot.com/o/images%2F1554003222273.jpg?alt=media&token=bf81db5a-ded5-4876-869c-f0f5265757bd");
        FirebaseFirestore db = FirebaseFirestore.getInstance();
        db.collection("incidents")
                .add(incident)
                .addOnSuccessListener(new OnSuccessListener<DocumentReference>() {
                    @Override
                    public void onSuccess(DocumentReference documentReference) {
                        Log.d("generator", "data has been generated.");
                    }
                });
    }
}
